version: 2
multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
